version: '3.8'

services:
  web:
    image: boda-web:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    stdin_open: true
    tty: true
